---
# Config file for automatic testing at travis-ci.org

sudo: required

language: minimal

os:
  - linux

services:
  - docker

# bail-out early for failures
fast_finish: true

before_install:
  #- git pull dcorre/gmadet:travis
  - docker build -t gmadet:travis -f Docker/Dockerfile.travis . || exit 1;

script:
  # run tests
  - docker run -v $(pwd):/home/newuser/gmadet/ gmadet:travis -c 'pytest tests' || exit 1;
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/.cache/pip

# perform coverage
after_success:
  - codecov
