---
# Config file for automatic testing at travis-ci.org

language: minimal

os:
  - linux

services:
  - docker

before_install:
  - sudo groupadd docker
  - sudo usermod -aG docker $USER 
  #- git pull dcorre/gmadet:travis
  - docker build -t gmadet:travis -f Docker/Dockerfile.travis . || exit 1;

script:
  # run tests
  - docker run -v $(pwd):/home/newuser/gmadet/ gmadet:travis -c 'python3.7 setup.py develop --user; pytest tests' || exit 1;
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/.cache/pip

# perform coverage
after_success:
  - codecov
